# Generated by Django 2.2.7 on 2020-07-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200317_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='melodia_logo.png', upload_to='profile_pics'),
        ),
    ]
